### ISSUE TITLE
Inventory bug #3

### ISSUE THREAD

**Issue by TheAz928** [BlockHorizons/BlockPets#102]
Pet inventories are still not being saved properly, items getting lost

**Comment by Sandertv** [comment]
I can't do anything with this. 'items getting lost' is not enough description. When do items get lost?

**Comment by TheAz928** [comment]
Sometimes after restart, or after owner getting killed, basically I've spotten the loses on level switch (maybe fixed by now), pet levelup,  after restart, after pet die

**Comment by MalakasPlayzMC** [comment]
Because I don't want to create another issue and I am not sure if this is a bug because of my PocketMine version but this is what I get when I start my server:

> 2017-10-29 [08:30:31] [Server thread/INFO]: Loading BlockPets v1.1.0
2017-10-29 [08:30:31] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '?'" (EXCEPTION) in "BlockPets_dev-228.phar/src/BlockHorizons/BlockPets/Loader" at line 342
2017-10-29 [08:30:31] [Server thread/CRITICAL]: Could not load plugin 'BlockPets'

**Comment by MalakasPlayzMC** [comment]
@Sandertv

**Comment by MalakasPlayzMC** [comment]
https://github.com/BlockHorizons/BlockPets/blob/master/src/BlockHorizons/BlockPets/Loader.php#L342

**Comment by Sandertv** [comment]
You're not running a server with the right PHP version. You need PHP 7.2, which is what PocketMine needs.

**Comment by MalakasPlayzMC** [comment]
Thanks

**Comment by MalakasPlayzMC** [comment]
Deleting posts...

**Comment by Muqsit** [comment]
This bug is fixed in https://github.com/BlockHorizons/BlockPets/commit/6231912712542932613ee6edbf84f4a4b250f62f. From this commit onwards, the Inventory in the database is updated every time a player closes the inventory.
