### ISSUE TITLE
All problems with this plugin.

### ISSUE THREAD

**Issue by ArceusMatt** [BlockHorizons/BlockPets#119]
I am using the latest version of pocketmine, on a dedicated server & also tested this plugin on ramshard.
Here's the following problems i found & should really be fixed otherwise this plugin just shouldn't be public:

- Some pets will freeze when trying to use the saddle on them(the pet will not unfreze unless x amount of time or the pet was killed.),
- Plugin does not cancel creating pets on error,
- Plugin should not be using a database if the author is not that good at sql which i am assuming because when you try to remove or clear the pet they actually don't go away they return if you relog, restart or x amount of time,
- Suggestion to use yaml files when a player first gets their pet & save the data in a yaml file instead of a database(this is much easier for you & the plugin to understand.),
- if you give the pet a high enough level it will either crash all players or crash the server,
- Suggestion limit the pet level to 1000,
- plugin will sometimes confuse the name argument & size argument then will deside to spawn the first pet & a second pet named after the size,
- Due to the whole database concept; it will sometimes not spawn the pet on restart or in general,
- Pet damage will damage the player aswell if they're close to the pet,
- Size & baby arguments should be not used for some mobs for example: Ender dragon,
- Suggestion handle what pet they're trying to use then see if it needs the size or baby argument,
- If riding pet & use sneak then it will crash all players nearby or crash server.

**Comment by Muqsit** [comment]
About these:
- Plugin should not be using a database if the author is not that good at sql which i am assuming because when you try to remove or clear the pet they actually don't go away they return if you relog, restart or x amount of time,
- Suggestion to use yaml files when a player first gets their pet & save the data in a yaml file instead of a database(this is much easier for you & the plugin to understand.),
**Short answer:** No, those flat files are too limited.
**Long answer:** We currently dont have any plans on data readability and probably never will due to the limitations YAML offers such as inability to store binary strings (which is what inventories are stored in).
YAML can still be supported but it will take 33% (or more) more space than what SQL databases would take. A better solution would be to have in-game commands that handle what you want to do with the data, rather than you manually modify the flat files.

- Suggestion limit the pet level to 1000
Why?

**Comment by ArceusMatt** [comment]
Not sure if this was pointed to his reply about yaml or to my pet level suggestion.
If it was about my suggestion...
When an entered level is over 1000 or so the pet crashes the entire server.

**Comment by Muqsit** [comment]
Yeah but that doesn't mean we need to remove it. In that case, we should remove the ability to ride entities, ability for players to sneak and /spawnpet rather than fixing them.

**Comment by Muqsit** [comment]
This is becoming extremely hard to maintain because of being a blob of various other issues (duplications, many of which have already been fixed), I'd suggest you create one issue/suggestion per issue.
